#!/bin/zsh

export SUDO_ASKPASS="$HOME/bin/askpass"

setxkbmap -layout pl
xmodmap ~/.Xmodmap

xsetroot -solid '#171824'
xbacklight -set 75
xset dpms 3600 7200 0
xset s off
~/bin/kbd-backlight -s 1

dunst > /dev/null 2> /dev/null &
